---
- hosts: all
  become: true

  roles:
    - docker

  vars:
    docker_sdk_for_python_install: true
    docker_compose_install: true
    docker_compose_version: "1.26.2"

    docker_daemon_configuration:
      bip: 192.168.0.1/24
      default_address_pools:
        - base: 172.80.0.0/16
          size: 24
        - base: 172.80.0.0/16
          size: 24
      dns:
        - 8.8.8.8
        - 8.8.4.4
      storage_driver: "overlay2"
      log_driver: "json-file"
      log_opts:
        max_size: "10m"
        max_file: "5"
        labels: "somelabel"
        env: "os,customer"
      tls: true
      tlsverify: true
      tlscacert: ""
      tlscert: ""
      tlskey: ""